export enum NotificationType {
  CUSTOM_EMAIL = 'CUSTOM_EMAIL',
  TEMPLATE_EMAIL = 'TEMPLATE_EMAIL',
  PHONE_MESSAGE = 'PHONE_MESSAGE',
  PHONE_CALL = 'PHONE_CALL',
  VERIFICATION_CODE = 'VERIFICATION_CODE',
  SEND_VERIFICATION_CODE = 'SEND_VERIFICATION_CODE'
}
