# This is a basic workflow that is manually triggered

name: Manual workflow

permissions:
  actions: read
  contents: read

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Manual Test'
        default: 'Main'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm install
      
    - name: Install Protocol Buffers Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Install Global Proto
      run: npm install -g protoc-gen-ts

    - name: Run custom bash script
      run: |
        chmod +x apps/notification-service/script/build-protos.sh
        apps/notification-service/script/build-protos.sh

    - name: Use NX
      uses: nrwl/nx-set-shas@v4

    - name: Build
      run: npx nx build notification-service

    - name: Test
      run: npx nx test notification-service
