name: NodeJS with Webpack

on:
  workflow_dispatch: 

permissions:
  actions: read
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.7.3]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm install

    - name: Run custom bash script
      run: |
        chmod +x apps/notification-service/script/build-protos.sh
        apps/notification-service/script/build-protos.sh

    - name: Use NX
    - uses: nrwl/nx-set-shas@v4

    - name: Build
      run: npx nx build notification-service

    - name: Test
      run: npx nx test notification-service
